default: &default
  host: localhost
  user: postgres
  password: postgres
  adapter: postgres
  skip_dumping_schema_sql: true

production:
  <<: *default
  db: opal

development:
  <<: *default
  db: opal_dev